### ISSUE TITLE
CakePHP 4.0 branch?

### ISSUE THREAD

**Issue by geoidesic** [burzum/cakephp-service-layer#18]
Is this on the roadmap?

**Comment by burzum** [comment]
I can see how much work it requires. A pull request is welcome as well if you could help.

**Comment by burzum** [comment]
@geoidesic I've upgrade it mostly and pushed the changes to the `develop` branch. There is one issue left when running the tests. You can do it or wait until I find time to finish it.

**Comment by dereuromark** [comment]
It is now ready and working - in master.

See demo: https://sandbox4.dereuromark.de/sandbox/service-examples/posts

**Comment by burzum** [comment]
This is done by the 2.0.0 release https://github.com/burzum/cakephp-service-layer/releases/tag/2.0.0
