### ISSUE TITLE
CakePHP 4.4.15 - I seem to have a problem with the Pagination class on the Pagination service

### ISSUE THREAD

**Issue by bouillerot** [burzum/cakephp-service-layer#35]
# Hello, I seem to have a problem 

## with the Pagination class on the Pagination service

- I get this error message ![Screenshot_20230728_122506](https://github.com/burzum/cakephp-service-layer/assets/101400827/e8f7e0e3-5e1b-4a5c-af56-ef65e56223af)

## However, I seem to have respected the documentation. 

- In my defense this one is really very dry.
- based on [Pagination-Service.md](https://github.com/burzum/cakephp-service-layer/blob/master/docs/Pagination-Service.md)

### Here are the different files and configurations I use

- I do not provide the view file because in view of the error message, the latter is detected in a Burzum file

```PHP
// config/app.php

use Burzum\CakeServiceLayer\Annotator\ClassAnnotatorTask\ServiceAwareClassAnnotatorTask;
use Burzum\CakeServiceLayer\Generator\Task\ServiceTask;
use Cake\Cache\Engine\FileEngine;
use Cake\Database\Connection;
use Cake\Database\Driver\Mysql;
use Cake\Log\Engine\FileLog;
use Cake\Mailer\Transport\MailTransport;

  'IdeHelper' => [
        'generatorTasks' => [
            ServiceTask::class
        ],
        'classAnnotatorTasks' => [
            ServiceAwareClassAnnotatorTask::class
        ],
    ],
```
```PHP
// src/Application.php

use Authentication\AuthenticationService;
use Authentication\AuthenticationServiceInterface;
use Authentication\AuthenticationServiceProviderInterface;
use Authentication\Identifier\IdentifierInterface;
use Authentication\Middleware\AuthenticationMiddleware;
use Cake\Core\Configure;
use Cake\Core\ContainerInterface;
use Cake\Datasource\FactoryLocator;
use Cake\Error\Middleware\ErrorHandlerMiddleware;
use Cake\Http\BaseApplication;
use Cake\Http\Middleware\BodyParserMiddleware;
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Http\MiddlewareQueue;
use Cake\ORM\Locator\TableLocator;
use Cake\Routing\Middleware\AssetMiddleware;
use Cake\Routing\Middleware\RoutingMiddleware;
use Cake\Routing\Router;
use Psr\Http\Message\ServerRequestInterface;


    public function bootstrap(): void
    {
        // Call parent to load bootstrap from files.
        parent::bootstrap();

        if (PHP_SAPI === 'cli') {
            $this->bootstrapCli();
            try {
                $this->addPlugin('IdeHelper');
            } catch (\Throwable $e) {
            }
        } else {
            FactoryLocator::add(
                'Table',
                (new TableLocator())->allowFallbackClass(false)
            );
        }

        /*
         * Only try to load DebugKit in development mode
         * Debug Kit should not be installed on a production system
         */
        if (Configure::read('debug')) {
            $this->addPlugin('DebugKit');
        }

        // Load more plugins here
        $this->addPlugin('Authentication');
        $this->addPlugin('BootstrapUI');
        $this->addPlugin('Cake/Queue');
        $this->addPlugin('Muffin/Trash'); // soft-deletion
        $this->addPlugin('Burzum/CakeServiceLayer');
    }
```
```PHP
// src/Service/MyUsersService.php

<?php

declare(strict_types=1);

namespace App\Service;

// use App\Model\Table\UsersTable;
use Burzum\CakeServiceLayer\Service\ServiceAwareTrait;
use Cake\Http\ServerRequest;
use Cake\ORM\Locator\LocatorAwareTrait;

class MyUsersService
{
    use LocatorAwareTrait, ServiceAwareTrait;

    protected $request;
    protected $Users;

    public function __construct(ServerRequest &$request)
    {
        $this->request = $request;
        $this->loadService('Pagination', [$request]);
        // $this->loadModel('Users'); // Undefined method loadModel I'm using CakePHP 4.4.15
        $this->Users = $this->fetchTable('Users');
    }

    public function getListForUser($userId, $queryParams)
    {
        $query = $this->Users->find();
        return $this->Pagination->paginate($query, $queryParams); // here I get the Intelliphense message : Undefined Property '$Pagination'.
    }
}
```
```PHP
// src/Controller/UsersController.php

    use MailerAwareTrait, ServiceAwareTrait;

    public const ACT_NOTIFY = 'notify';
    public const ACT_IMPERSONATE = 'impersonate';

    public function initialize(): void
    {
        parent::initialize();

        $this->loadService('MyUsers', [$this->getRequest()]);
        $this->paginate += [
            'contain' => ['Roles'],
            'limit' => 3, // 20 by default
        ];
    }

    public function index()
    {
        $users =
            $this->MyUsers->getListForUser(
                $this->getLoggedInUserAsUser()->id,
                $this->getRequest()
            );
        $this->set('users', 'paginationKeys');
    }

```

## Here are the questions

- After re-reading and double-checking the code against the documentation several times. 
    - Especially the use of "USE" and "TRAIT". 
- I have to admit to being stuck. 
- I even copied the PaginationService.php file into my own Service directory
    - ![Screenshot_20230728_131301](https://github.com/burzum/cakephp-service-layer/assets/101400827/5421b69e-1d9f-4a16-94c9-04a1e7ee744f)
    - that action generate an error message when running : composer annotate : 
        - PHP Fatal error:  Cannot declare class Burzum\CakeServiceLayer\Service\PaginationService, because the name is already in use in /var/www/html/src/Service/PaginationService.
    - So I removed it from my repertory.
    - For information here is the reult of same command 
    - ![Screenshot_20230728_132041](https://github.com/burzum/cakephp-service-layer/assets/101400827/851138fc-d57d-44bb-816f-41952a32284c)
- Did I miss a detail from the documentation? 
- Did I misinterpret or misunderstand something? 
- Any explanation and/or help will be greatly appreciated.

**Comment by dereuromark** [comment]
I must admit: I dont use the pagination part of the plugin.
Maybe @burzum has some insights on this one.

**Comment by floriankraemer** [comment]
@bouillerot thanks for this excellent report, it's rare to see such a well written repot! 👍 

I really feel sorry because of that to tell you that I'm not using CakePHP anymore for a little more than ~2.5 years now, the error is probably related to the DI library or the configuration, I'm not sure to be honest, I would have to look into this as well. If I have the time and mood I'll try to look into this but no guarantee I'll do it at all and expect it to take a few days before I get to it.

@dereuromark I thought you are the new maintainer? 😸

**Comment by dereuromark** [comment]
Well, I am not gonna deep dive into debugging it right now :)

**Comment by bouillerot** [comment]
@floriankraemer  Thank you for the compliment it's nice. I had seen that you no longer provide contributions on this repository. However hope gives life.

@dereuromark  As I am just a simple consumer for this repository. I will therefore adapt and do as you do and not use the plugin's pagination service.

**Comment by dereuromark** [comment]
Given the error message it looks for Pagination instead of PaginationService class
So try to find out why, or if the error message is just misleading.
E.g. try

    $this->loadService('PaginationService')
    
and see if that finds it.
Then it internally seems to not add the "Service" suffix for some reason.

**Comment by bouillerot** [comment]
@dereuromark  Courage ! 

![Screenshot_20230728_135350](https://github.com/burzum/cakephp-service-layer/assets/101400827/11e18a89-80ef-459c-bf57-f18880f7d6c7)

**Comment by floriankraemer** [comment]
> Thank you for the compliment it's nice. 

@bouillerot it's true, I really appreciate it, it's rare to get proper reports and I even got sometimes pretty unfriendly, very arrogant and demanding requests like "Hey, fix that ASAP!" that did not include useful information or "Do this feature NOW!". Which is one reason why I stopped spending a lot time doing open source and maintenance - besides the lack of time when you get kids. 😄

**Comment by dereuromark** [comment]
namespace Burzum\CakeServiceLayer\Service;
    
You need to probably debug why it cannot find or rather doesnt look for the service in the plugin.
That said, I am fairly certain the docs are wrong, since this being in the plugin itself cannot ever be called or found this way.
I would rather think it is

    $this->loadService('Burzum/CakeServiceLayer.Pagination')
    
etc

**Comment by bouillerot** [comment]
@dereuromark You got it ! 

![Screenshot_20230728_140303](https://github.com/burzum/cakephp-service-layer/assets/101400827/5a9162ef-49e2-43bc-88aa-9ffbb2b2d91b)

**Comment by dereuromark** [comment]
Feel free to open a PR once you found what needs to be corrected. We will review and merge in a time sensitive manner.

**Comment by bouillerot** [comment]
@dereuromark  @floriankraemer  Thank you for your great responsiveness! 

OK I will open a PR once I found what needs to be corrected.
