### ISSUE TITLE
Call to a plugin's Service results in an error

### ISSUE THREAD

**Issue by PaulHendriks** [burzum/cakephp-service-layer#38]
I'm migrating from CakePHP4.5 to 5.0.
There is a plugin which contains a Service.
In a Table of a project, i initialize the service as: 

```
class SomeTable extends Table
{
    use ServiceAwareTrait;

    public function initialize(array $config): void
    {
        parent::initialize($config);
        $this->loadService('SomePlugin.Foo');
    }
}
```

Which results in this error:
```__construct(): Argument #1 ($config) must be of type array, string given```

When i dump $args in ServiceLocator on line 83, it shows ```SomePlugin.Foo```.
Somehow the name of the Service is handled as $config.

Workaround:

```
        $this->loadService('SomePlugin.Foo', ['config' => []]);
```

This might be related to: https://github.com/cakephp/cakephp/issues/17435

**Comment by dereuromark** [comment]
I havent used this with plugin syntax yet, only normally
I wonder what goes wrong here, config is the 2nd arg, not first.

Sounds like a cast or defaulting to empty array is missing or sth?

**Comment by dereuromark** [comment]
Or is https://github.com/cakephp/cakephp/pull/17580 fixing it for you here too?

**Comment by dereuromark** [comment]
I cannot reproduce this, using the same

        $this->loadService('SomePlugin.Foo');
        
call works for me with the first part of ServiceLocator::_create()

        if (empty($config)) {
            return new $class();
        }

**Comment by PaulHendriks** [comment]
It's related to https://github.com/cakephp/cakephp/issues/17435
When i revert those changes, the error with loading the service is gone.
