### ISSUE TITLE
Mocking

### ISSUE THREAD

**Issue by dereuromark** [burzum/cakephp-service-layer#8]
Refs https://github.com/burzum/cakephp-service-layer/issues/4

I would like to discuss the best stategy of mocking more deeply nested API calls and stuff
(and no, phpvcr and other tools are not feasable in those cases).
With current cake semi-DI and and integration testing this is just not possible.

I modified this library a bit to allow for the following two alternatives of mocking.
One is using a god like container via Configure to transport mocks, the other one is probably a bit cleaner, using a special test-only MockedServiceLocator instead of default ServiceLocator.

Similar things could also be done for TableRegistry and other classes I guess?
Whats the feedback on those? Or what is a better alternative?

How the test works:
- the API just returns a string, and I mock the API result in a 2nd part to return sth else.

```php
namespace App\Test\TestCase\Controller;

use App\Controller\DemoController;
use App\Service\Bar\BazService;
use Burzum\Cake\TestSuite\MockedServiceLocator;
use Cake\Core\Configure;
use Cake\TestSuite\IntegrationTestCase;

    /**
     * Test index method
     *
     * @return void
     */
    public function testIndex()
    {
        $this->disableErrorHandlerMiddleware();

        $this->get('/demo');

        $this->assertResponseCode(200);

        $x = Configure::read('test-string');
        $this->assertSame('original', $x);
    }

    /**
     * Test index method
     *
     * @return void
     */
    public function testIndexMocked()
    {
        $this->disableErrorHandlerMiddleware();

        $mockedService = $this->getMockBuilder(BazService::class)->setMethods(['doSth'])->getMock();
        $mockedService->expects($this->once())->method('doSth')->willReturn('faked');

        Configure::write('Services.' . 'Bar/Baz', $mockedService);

        $this->get('/demo');

        $this->assertResponseCode(200);

        $x = Configure::read('test-string');
        $this->assertSame('faked', $x);
    }

    /**
     * Test index method
     *
     * @return void
     */
    public function testIndexMockedAlternative()
    {
        DemoController::setDefaultServiceLocator(MockedServiceLocator::class);

        $this->disableErrorHandlerMiddleware();

        $mockedService = $this->getMockBuilder(BazService::class)->setMethods(['doSth'])->getMock();
        $mockedService->expects($this->once())->method('doSth')->willReturn('faked');

        MockedServiceLocator::mock(BazService::class, $mockedService);

        $this->get('/demo');

        $this->assertResponseCode(200);

        $x = Configure::read('test-string');
        $this->assertSame('faked', $x);
    }
```

**Comment by dereuromark** [comment]
The diff of plugin change is here: https://github.com/dereuromark/cakephp-service-layer/compare/master...dereuromark:test-mocking-alternatives
Contains both alternatives, so the actual PR for each would be a subset.

**Comment by burzum** [comment]
@dereuromark I've checked the code, I dislike that you introduces the need to call Configure and that for the sake of being able to access it made the locator static? Why cant you simply create a mock of the locator and set it via setLocator()?

**Comment by burzum** [comment]
@dereuromark any feedback on this?
